use std::sync::{Arc, OnceLock};
use pond_adapters_weather::WeatherProvider;
use pond_core::ports::device_registry::DeviceRegistry;
use pond_core::ports::memory_repository::MemoryRepository;
use pond_core::ports::recipe::AgentRecipeRepository;
use pond_core::ports::scheduler::SchedulerPort;
use pond_core::ports::settings::SettingsRepository;
use pond_core::ports::skill::UserSkillRepository;
use pond_core::ports::tool_caller::ToolCaller;
use crate::giap_server::GiapMcpServer;
use rmcp::ServiceExt;
use tokio::io::DuplexStream;

pub struct GiapServiceHandles {
    pub weather:         Option<Arc<dyn WeatherProvider>>,
    pub device_registry: Arc<dyn DeviceRegistry + Send + Sync>,
    pub scheduler:       Option<Arc<dyn SchedulerPort>>,
    pub settings_repo:   Arc<dyn SettingsRepository + Send + Sync>,
    pub memory_repo:     Arc<dyn MemoryRepository + Send + Sync>,
    pub skill_repo:      Arc<dyn UserSkillRepository + Send + Sync>,
    pub recipe_repo:     Arc<dyn AgentRecipeRepository + Send + Sync>,
    /// Shared HTTP client for tools that fetch external data (Wikipedia, etc.).
    pub http_client:     reqwest::Client,
    /// Tool-calling specialist model. When `Some`, empty tool arguments are
    /// re-generated by this small model before the tool executes.
    pub tool_caller:     Option<Arc<dyn ToolCaller>>,
    /// The most recent user message, updated before each agent turn.
    /// Used as fallback when a tool is called with empty parameters
    /// (common with small local models that struggle with tool-call schemas).
    pub last_user_message: tokio::sync::RwLock<String>,
}

static GIAP_SERVICES: OnceLock<Arc<GiapServiceHandles>> = OnceLock::new();

pub fn init_giap_services(services: Arc<GiapServiceHandles>) {
    let _ = GIAP_SERVICES.set(services);
}

/// Update the last user message so tools can use it as a fallback when the
/// model calls a tool with empty parameters.
pub async fn set_last_user_message(msg: &str) {
    if let Some(handles) = GIAP_SERVICES.get() {
        *handles.last_user_message.write().await = msg.to_string();
    }
}

/// Tool Agent entry point: look up a topic on Wikipedia.
///
/// Called by the route handler BEFORE the main LLM runs. Uses the same
/// HTTP helpers as the MCP tool but bypasses the Goose agentic loop entirely.
/// Returns `Some(article_text)` on success, `None` if the lookup fails.
pub async fn try_wikipedia_lookup(query: &str) -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let server = GiapMcpServer::new(services.clone());
    let cleaned = crate::giap_server::clean_query_for_search(query);
    let topic = if cleaned.is_empty() { query.trim() } else { cleaned.as_str() };
    if topic.is_empty() { return None; }

    println!("[tool-agent] wikipedia lookup for {:?}", topic);

    // Try direct title first, then search fallback
    match server.fetch_article_summary(topic).await {
        Ok(text) => {
            println!("[tool-agent] direct hit for {:?}", topic);
            Some(text)
        }
        Err(crate::giap_server::WikiFetchError::NotFound) => {
            println!("[tool-agent] not found, searching for {:?}", topic);
            server.search_and_fetch_best(topic).await.ok()
        }
        Err(_) => None,
    }
}

/// Tool Agent entry point: get current weather.
pub async fn try_weather_lookup() -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let weather = services.weather.as_ref()?;
    match weather.current().await {
        Ok(data) => {
            println!("[tool-agent] weather fetched successfully");
            Some(data.as_context_block())
        }
        Err(e) => {
            println!("[tool-agent] weather fetch failed: {e}");
            None
        }
    }
}

/// Unified Tool Agent: execute a specific tool by name.
/// Called after the classifier decides which tool is needed.
/// Returns `Some(result_text)` on success.
pub async fn try_tool_agent(tool: &str, message: &str) -> Option<String> {
    println!("[tool-agent] executing tool={:?} for message={:?}", tool, message);
    match tool {
        "weather" => try_weather_lookup().await,
        "save_memory" => try_save_memory(message).await,
        "recall_memory" => try_recall_memory(message).await,
        "devices" => try_list_devices().await,
        "schedules" => try_list_schedules().await,
        "wikipedia" | _ => try_wikipedia_lookup(message).await,
    }
}

/// Save a memory fragment from the user's message.
async fn try_save_memory(message: &str) -> Option<String> {
    use pond_core::domain::memory::MemoryFragment;
    let services = GIAP_SERVICES.get()?;
    let cleaned = crate::giap_server::clean_query_for_search(message);
    let content = if cleaned.is_empty() { message.trim().to_string() } else { cleaned };
    let fragment = MemoryFragment {
        id: uuid::Uuid::new_v4().to_string(),
        profile_id: None,
        session_id: None,
        content: content.clone(),
        embedding: None,
        source: "tool_agent".to_string(),
        tags: vec![],
        created_at: chrono::Utc::now(),
    };
    match services.memory_repo.add(fragment).await {
        Ok(_) => {
            println!("[tool-agent] memory saved: {:?}", content);
            Some(format!("Memory saved: {}", content))
        }
        Err(e) => {
            println!("[tool-agent] memory save failed: {e}");
            None
        }
    }
}

/// Recall recent memories, optionally filtered by the user's query.
async fn try_recall_memory(message: &str) -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let memories = services.memory_repo.search_recent(None, 10).await.ok()?;
    if memories.is_empty() {
        return Some("No saved memories found.".to_string());
    }
    let cleaned = crate::giap_server::clean_query_for_search(message).to_lowercase();
    let filtered: Vec<_> = if cleaned.is_empty() {
        memories
    } else {
        memories.into_iter()
            .filter(|m| m.content.to_lowercase().contains(&cleaned))
            .collect()
    };
    if filtered.is_empty() {
        return Some(format!("No memories found matching '{}'.", cleaned));
    }
    let text = filtered.iter()
        .map(|m| format!("- [{}] {}", m.created_at.format("%Y-%m-%d"), m.content))
        .collect::<Vec<_>>()
        .join("\n");
    println!("[tool-agent] recalled {} memories", filtered.len());
    Some(text)
}

/// List registered devices.
async fn try_list_devices() -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let devices = services.device_registry.list_devices().await.ok()?;
    if devices.is_empty() {
        return Some("No devices registered.".to_string());
    }
    let text = devices.iter()
        .map(|d| format!("- {} ({}): {}", d.name, d.device_type, if d.is_online { "online" } else { "offline" }))
        .collect::<Vec<_>>()
        .join("\n");
    println!("[tool-agent] listed {} devices", devices.len());
    Some(text)
}

/// List scheduled tasks.
async fn try_list_schedules() -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let scheduler = services.scheduler.as_ref()?;
    let tasks = scheduler.list_tasks().await.ok()?;
    if tasks.is_empty() {
        return Some("No scheduled tasks.".to_string());
    }
    let text = tasks.iter()
        .map(|t| format!("- {} [{}]: {} ({})", t.label, t.id, t.cron, if t.paused { "paused" } else { "active" }))
        .collect::<Vec<_>>()
        .join("\n");
    println!("[tool-agent] listed {} schedules", tasks.len());
    Some(text)
}

pub fn spawn_giap_server(reader: DuplexStream, writer: DuplexStream) {
    let services = GIAP_SERVICES
        .get()
        .expect("GIAP services not initialized — call init_giap_services() first")
        .clone();
    let server = GiapMcpServer::new(services);
    tokio::spawn(async move {
        match server.serve((reader, writer)).await {
            Ok(running) => {
                let _ = running.waiting().await;
            }
            Err(e) => {
                tracing::error!("GIAP MCP server failed to start: {e}");
            }
        }
    });
}
